
server.port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cars
    #url: jdbc:mysql://localhost:3306/cars?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
    username: byzthr
    password: 7072

  jpa:
    #database-platform: org.hibernate.dialect.MySQLDialect
    show_sql: true
    properties.hibernate:
      format_sql: true
      highlight_sql: true
      generate_statistics: true
    hibernate:
      ddl-auto: update
      generate-ddl: true